name: core
resolution: workspace
description: core
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1
  dart_mappable: ^4.6.1
  jaspr: ^0.22.2

dev_dependencies:
  build_runner: ^2.11.1
  dart_mappable_builder: ^4.6.4
  very_good_analysis: ^10.1.0
