name: core
description: core
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1
  dart_mappable: ^4.6.1
  jaspr: ^0.21.3

dev_dependencies:
  build_runner: ^2.8.0
  dart_mappable_builder: ^4.6.1
  very_good_analysis: ^10.0.0
