name: core
description: core
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1
  dart_mappable: ^4.5.0
  jaspr: ">=0.20.0 <0.22.0"

dev_dependencies:
  build_runner: ^2.5.4
  dart_mappable_builder: ^4.5.0
  very_good_analysis: ^9.0.0
