name: ui
resolution: workspace
description: ui
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  jaspr: ^0.22.2
  jaspr_router: ^0.8.1
  universal_web: ^1.1.1+1

dev_dependencies:
  very_good_analysis: ^10.1.0
