name: portfolio
resolution: workspace
description: A portfolio website made with Jaspr.
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  core: ^1.0.0
  dotenv: ^4.2.0
  get_it: ^9.2.0
  github: ^9.25.0
  jaspr: ^0.22.2
  jaspr_content: ^0.4.5
  jaspr_riverpod: ^0.4.4
  jaspr_router: ^0.8.1
  path: ^1.9.1
  resume: ^1.0.0
  ui: ^1.0.0
  universal_web: ^1.1.1+1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.11.1
  build_web_compilers: ^4.4.11
  jaspr_builder: ^0.22.2
  jaspr_lints: ^0.6.0
  very_good_analysis: ^10.1.0

jaspr:
  mode: static
